// list.js — se puede editar a mano o con editor-list.html
// Mismo formato en ambos idiomas; el orden de categorías y elementos debe coincidir.
const listData = {
  es: `
Juegos PC (emoji.windows)=🎮 (emoji.windows)=:
  -Alien Shooter "https://gogunlocked.com/alien-shooter-expansions-free-download/"
  -Alien Shooter 2: Reloaded "https://gogunlocked.com/alien-shooter-2-reloaded-free-download/"
  -Call of Duty Mobile PC [Versión china] "https://codm.qq.com/main.shtml"
  -Call of Duty: Black Ops 1 "https://pivigames.blog/call-of-duty-black-ops-zombies-y-multiplayer-online/"
  -Call of Duty: Black Ops 2 "https://pivigames.blog/call-of-duty-black-ops-2-zombies-multiplayer-con-bots/"
  -Call of Duty: Modern Warfare 3 "https://pivigames.blog/call-of-duty-moder-warfare-3-con-multijugador-online/"
  -CB Servers Launcher [CoD Launcher] "https://docs.cbservers.xyz/launcher"
  -Clone Drone in the Danger Zone "https://www.mediafire.com/file/cs7iz3ckjpuoh6b/Clone_Drone_in_the_Danger_Zone.zip/file"
  -Cuphead "https://angel06a.github.io/angel06web/games/pc/cuphead/"
  -Downwell "https://elenemigos.com/app/downwell-descargar-gratis/21530"
  -Dragon Ball FighterZ "https://steamunlocked.org/dragon-ball-fighterz-free-download/"
  -Dragon Ball Sparking ZERO "https://pivigames.blog/dragon-ball-sparking-zero-oferta-25/"
  -Exiled Kingdoms "https://gogunlocked.com/exiled-kingdoms-free-download/"
  -Far Cry 3 "https://steamunlocked.org/far-cry-3-deluxe-edition-free-download/"
  -Flare "https://flarerpg.org/download/"
  -GTA III "https://www.blizzboygames.net/gta-iii-pc-full-espanol/"
  -GTA IV "https://pivigames.blog/grand-theft-auto-iv-episodes-from-liberty/"
  -GTA V "https://pivigames.blog/grand-theft-auto-v-premium-online-edition/"
  -GTA: San Andreas "https://www.blizzboygames.net/gta-san-andreas-pc-full-espanol/"
  -GTA: Vice City "https://www.blizzboygames.net/gta-vice-city-pc-full-espanol/"
  -Half-Life 1 Anthology "https://pivigames.blog/half-life-goty-edition/"
  -Halo Combat Evolved "https://steamunlocked.org/halo-combat-evolved-free-download/"
  -Injustice: Gods Among Us "https://steamunlocked.org/injustice-gods-among-us-ultimate-edition-free-download/"
  -Killer Instinct "https://pivigames.blog/killer-instinct/"
  -Left 4 Dead 2 "https://pivigames.blog/left-4-dead2-online-steam-ultima-version/"
  -Mario Kart 64 Port "https://github.com/sonicdcer/MarioKart64Recomp/releases" "https://vimm.net/vault/2649" *Descargar* *Rom*
  -Minecraft Bedrock "https://www.xbox.com/es-ES/games/store/minecraft-for-windows/9NBLGGH2JHXJ" "https://online-fix.me/games/sandbox/16708-minecraft-for-windows-po-seti.html" *Descargar* *OnlineFix*
  -Mortal Kombat Komplete Edition "https://steamunlocked.org/mortal-kombat-komplete-edition-free-download/"
  -Nidhogg 2 "https://steamunlocked.org/nidhogg-2-free-download/"
  -Nidhogg "https://steamunlocked.org/nidhogg-free-download/"
  -Naruto Shippuden: Ultimate Ninja STORM 3 "https://steamunlocked.org/naruto-shippuden-ultimate-ninja-storm-3-full-burst-hd-free-download/"
  -Pureya "https://steamunlocked.org/pureya-free-download/"
  -Quake III Arena "https://steamunlocked.org/quake-iii-arena-free-download/" "https://ioquake3.org/" *Juego Base* *Ioquake3*
  -Rayman Legends "https://angel06a.github.io/angel06web/games/pc/rayman-legends/"
  -Serious Sam HD "https://steamunlocked.org/serious-sam-hd-the-second-encounter-free-download/"
  -Slayin DX "https://steamunlocked.org/slayin-dx-free-download/"
  -Slime Rancher "https://rentry.co/dzwd6zp4"
  -Sonic The Hedgehog 3D "https://rentry.co/m46az9tz"
  -Spore "https://steamunlocked.org/spore-collection-free-download/"
  -Street Fighter X Tekken "https://angel06a.github.io/angel06web/games/pc/SFTK/"
  -Super Mario 64 Port "https://sm64coopdx.com/" "https://vimm.net/vault/2764" *Descargar* *Rom*
  -Super Smash Flash 2 "https://www.supersmashflash.com/play/ssf2/downloads/"
  -The Legend of Zelda Port "https://www.shipofharkinian.com/" "https://vimm.net/vault/2637" *Descargar* *Rom*
  -Ultimate Marvel vs Capcom 3 "https://rentry.co/3b2zfkhf"
  -Undertale "https://pivigames.blog/undertale-en-espanol/"
Programas PC (emoji.windows)=⚙️ (emoji.windows)=:
  -Atlas OS [Optimizador] "https://github.com/Atlas-OS/Atlas"
  -Autoruns [Registro de Windows] "https://www.google.com/url?q=https://download.sysinternals.com/files/Autoruns.zip&sa=D&source=docs&ust=1741690293775013&usg=AOvVaw3r6f1YvR1doRmskUjrBNyS"
  -BleachBit [Limpieza] "https://www.bleachbit.org/"
  -Bulk Crap Uninstaller [Limpieza] "https://www.bcuninstaller.com/"
  -CCleaner [Optimizador][Limpieza] "https://taiwebs.org/herramientas/ccleaner/"
  -CHDman [Compresor] "https://www.mediafire.com/file/gpehgmsgtnk3yz3/CHDman-0.276.zip/file"
  -CompactGUI [Optimizador][Compresor] "https://compactgui.org/"
  -DirectX Runtime [Instalador] "https://www.techpowerup.com/download/directx-redistributable-runtime/"
  -DXVK [DirectX a Vulkan] "https://github.com/Digger1955/dxvk-gplall/releases" "https://github.com/doitsujin/dxvk/releases" *LowLatency* *Original*
  -Filmora [Editor de Video] "https://taiwebs.org/programas/wondershare-filmora-portable/"
  -HidHide [Ocultar Control] "https://github.com/nefarius/HidHide"
  -IdeapadToolkit [Alternativa a Lenovo Vantage] "https://github.com/reagcz/IdeapadToolkit" "https://www.mediafire.com/file/iehwb5o2yq2oenu/PowerBattery.dll/file" *Descargar* *Archivo Necesario*
  -IObit Advanced SystemCare [Optimizador][Limpieza] "https://advanced-systemcare-ultimate.updatestar.com/es"
  -IObit Driver Booster [Drivers] "https://iobit-driver-booster-pro.updatestar.com/es"
  -IObit Unlocker [Desbloquear Archivos] "https://www.iobit.com/es/iobit-unlocker.php"
  -ITop Easy Desktop [Organizar Carpetas] "https://itop-easy-desktop.updatestar.com/es"
  -LenovoController [Alternativa a Lenovo Vantage] "https://github.com/ViRb3/LenovoController"
  -Mirillis Action! [Grabador de pantalla] "https://descargaspcpro.net/mirillis-action-programa-para-grabar-la-pantalla-y-videojuegos-de-tu-pc/"
  -MPO-GPU-FIX [Optimizador] "https://github.com/RedDot-3ND7355/MPO-GPU-FIX"
  -O&O ShutUp10++ [Desactivar Servicios] "https://www.oo-software.com/es/shutup10"
  -OptimizerDuck [Optimizador] "https://optimizerduck.vercel.app/"
  -Photopea Offline [Editor de Imagen][Por Angel06] "https://www.mediafire.com/file/mi1kpb5oyvaint8/Photopea_Offline.zip/file"
  -Process Lasso [Optimizador] "https://descargaspcpro.net/bitsum-process-lasso-pro-herramienta-de-optimizacion-y-automatizacion-de-la-cpu-en-tiempo-real/"
  -qBittorrent "https://www.qbittorrent.org/"
  -Quick CPU [Optimizador] "https://coderbag.com/product/quickcpu"
  -Ratiborus KMS Tools [Activador] "https://descargaspcpro.net/ratiborus-kms-tools-coleccion-de-activadores-para-todos-los-windows-y-office/"
  -RetroBat [Frontend][Emular] =🕹️= "https://www.retrobat.org/descargar/"
  -TeraBox [Almacenamiento en la Nube] "https://www.terabox.com/"
  -UniGetUI [Actualizador] "https://devolutions.net/unigetui/"
  -Upscayl [Escalar imagen] "https://upscayl.org/download"
  -VigemBus [Driver Control] "https://vigembusdriver.com/download/"
  -Visual C++ Runtime [Instalador] "https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/"
  -WinRAR [Comprimir] "https://winrar.es/descargas" "https://www.mediafire.com/file/fpjwybjxfk5emug/rarreg.key/file" *Descargar* *Crack*
  -Wintoys [Optimizador][Limpieza] "https://apps.microsoft.com/detail/9p8ltpgcbzxd?hl=es-ES&gl=ES"
  -X360CE [Emular Control] =🎮= "https://www.x360ce.com/"
  -XOutput [Emular Control] =🎮= "https://xoutput.org/"
Juegos Android (emoji.android)=🎮 (emoji.android)=:
  -Alien Shooter "https://www.mediafire.com/file/qtxntb41f2tfaib/Alien_Shooter_1.2.5.apk/file"
  -Call of Duty: Black Ops Zombies "https://www.mediafire.com/file/a9cb3i70ft7ms7n/COD_BOZ_1.0.11.zip/file"
  -Crash Bandicoot: On the Run [Sin conexión] "https://agmod.org/crash-bandicoot-on-the-run-full-offline-apk-obb/"
  -Cuphead "https://apkvision.org/games/action/cuphead-100069/"
  -Dead Effect 2 "https://agmod.org/dead-effect-2/"
  -Dead Space "https://agmod.org/dead-space/"
  -Downwell "https://www.mediafire.com/file/kgf4ethmk88byy3/Downwell_1.1.1.apk/file"
  -Dragon Ball Tap Battle "https://www.mediafire.com/file/sga4y11ur7s44b3/Dragon_Ball_Tap_Battle_1.4.apk/file"
  -Exiled Kingdoms "https://apkvision.org/games/role-playing/exiled-kingdoms-rpg-10725/"
  -Fast Food Rampage "https://www.mediafire.com/file/g2f8trc7ezkqrmy/Fast_Food_Rampage_1.0.8.apk/file"
  -GTA III "https://apkvision.org/games/action/grand-theft-auto-3-apk-3166/"
  -GTA: Chinatown Wars "https://apkvision.org/games/action/gta-chinatown-wars-8293/"
  -GTA: Liberty City Stories "https://apkvision.org/games/action/gta-liberty-city-stories-8337/"
  -GTA: San Andreas "https://apkvision.org/games/action/grand-theft-auto-san-andreas-apk-106-2824/"
  -GTA: Vice City "https://apkvision.org/games/action/grand-theft-auto-vice-city-apk-2820/"
  -Lego DC Mighty Micros "https://www.mediafire.com/file/1i6ga7bi2qo1voh/LEGO_DC_Mighty_Micros_1.7.1418.apk/file"
  -Minecraft Bedrock "https://mcpelife.com/download/"
  -NARUTO: Ultimate Ninja STORM "https://apkvision.org/games/action/naruto-ultimate-ninja-storm-124113/"
  -Paladog "https://www.mediafire.com/file/1xbi8es1hh3sscx/Paladog_2.2.0.apk/file"
  -Pureya "https://www.mediafire.com/file/6n6i3m4cso48zfd/Pureya_1.0.15.apk/file"
  -Run & Gun: Banditos "https://www.mediafire.com/file/cu23w1yl9t4qp64/Run_%2526_Gun_BANDITOS_1.3.2.apk/file"
  -Slayin "https://www.mediafire.com/file/aya455c8ig96hjw/Slayin_2.0.13.apk/file"
  -Slime Rancher "https://apkvision.org/games/action/slime-rancher-106836/"
  -Street Fighter IV CE "https://apkvision.org/games/action/street-fighter-iv-ce-netflix-128855/"
  -Super Mario 64 Port "https://github.com/ManIsCat2/sm64coopdx/releases" "https://vimm.net/vault/2764" *Descargar* *Rom*
  -The Legend of Zelda Port "https://github.com/linkzenic/Shipwright-Android/releases" "https://vimm.net/vault/2637" *Descargar* *Rom*
  -Zombie Avengers Dreamsky Stickman War "https://www.mediafire.com/file/7qmtqoinva2itn4/Zombie_Avengers_Dreamsky_Stickman_War_2.0.3.apk/file"
Programas Android (emoji.android)=⚙️ (emoji.android)=:
  -ARMSX2 [Emular PS2] =🕹️= "https://play.google.com/store/apps/details?id=come.nanodata.armsx2"
  -Azahar [Emular 3DS] =🕹️= "https://play.google.com/store/apps/details?id=io.github.lime3ds.android"
  -CapCut Pro [Editor de Video] "https://www.mediafire.com/file/wvhjm75wj4cqdoc/CapCut+Pro+v13.9.0_(AndroidApkData.net).apk/file"
  -Daijishō [Frontend][Emular] =🕹️= "https://play.google.com/store/apps/details?id=com.magneticchen.daijishou"
  -Filmora [Editor de Video] "https://apkpure.com/es/filmora-movie-video-editor/com.wondershare.filmorago"
  -Gestor de archivos + "https://apkretro.com/file-manager-premium-apk-download/"
  -LibreTorrent "https://f-droid.org/es/packages/org.proninyaroslav.libretorrent/"
  -Linkboy [Emular GBA & GBC] =🕹️= "https://play.google.com/store/apps/details?id=com.pixelrespawn.linkboy"
  -LuckyPatcher "https://www.mediafire.com/file/rej7uf1t7w48x0u/luckypatcher.apk/file"
  -M64Plus FZ Pro [Emular N64] =🕹️= "https://apkretro.com/m64plus-fz-pro-emulator-apk-full-android/"
  -MAME4droid Current [Emular ARCADE] =🕹️= "https://github.com/seleuco/MAME4droid-Current/releases"
  -NES.Emu [Emular NES] =🕹️= "https://apkretro.com/nes-emu-apk-download/"
  -Pizza Boy GBA Pro [Emular GBA] =🕹️= "https://apkretro.com/pizza-boy-gba-pro-apk-download/"
  -PPSSPP Gold [Emular PSP] =🕹️= "https://apkretro.com/ppsspp-gold-apk-download/"
  -RAR [Premium desbloqueado] "https://apkretro.com/rar-premium-apk-download/"
  -ReVanced Manager Plus "https://vanced.to/revanced-manager"
  -Super Archivo "https://liteapks.com/super-file.html"
  -VPN Super Unlimited Proxy [Premium desbloqueado] "https://liteapks.com/vpn-super-unlimited-proxy.html"
Páginas Web (emoji.web)=(emoji.web)=:
  -Bios [Roms][Emular] =🕹️= "https://github.com/Angel06a/Bios-RetroBat"
  -BT4 HD [Pack de texturas DBZ BT4][Por Angel06] =⚙️= "https://angel06a.github.io/BT4-HD/"
  -BuscaMinas [Por Angel06] =🎮= "https://angel06a.github.io/angel06web/hub/minesweeper/" *Jugar*
  -DaedalOS [Escritorio] =⚙️= "https://dustinbrett.com/" *Utilizar*
  -Flappy Bird =🎮= "https://emupedia.net/emupedia-game-flappy-bird/" *Jugar*
  -Friday Night Funkin =🎮= "https://ninja-muffin24.itch.io/funkin" *Jugar*
  -GamesGX [Ps2 Roms][Emular] =🕹️= "https://www.gamesgx.net/"
  -Icon Converter =⚙️= "https://redketchup.io/icon-converter" *Utilizar*
  -Jetpack Joyride =🎮= "https://emupedia.net/emupedia-game-jetpack-joyride/" *Jugar*
  -MarkEditor [Por Angel06] =⚙️= "https://angel06a.github.io/angel06web/hub/markeditor/" *Utilizar*
  -NoPayStation [Ps3 Roms][Emular] =🕹️= "https://nopaystation.com/browse"
  -OpenLara [Tomb Raider] =🎮= "https://emupedia.net/emupedia-game-tomb-raider/" *Jugar*
  -Photopea [Editor de Imagen] =⚙️= "https://www.photopea.com/" *Utilizar*
  -Puter [Escritorio] =⚙️= "https://puter.com/"
  -RetroGames [Emular] =🕹️= "https://www.retrogames.onl/" *Jugar*
  -ROMSFUN [Roms][Emular] =🕹️= "https://romsfun.com/"
  -Slash FRVR [Fruit Ninja] =🎮= "https://slash.frvr.com/es/" *Jugar*
  -Subway Surfers =🎮= "https://g2.igroutka.ru/games/164/ZXLa594fek6p7nVR/10/subway_surfers_classic/" *Jugar*
  -Super Mario 64 Port =🎮= "https://notan127.github.io/SM64-PC-Port-WebGL/" *Jugar*
  -Temple Run 2 =🎮= "https://emupedia.net/emupedia-game-temple-run2/" *Jugar*
  -TempMail =⚙️= "https://temp-mail.org/es/" *Utilizar*
  -The Binding of Isaac =🎮= "https://emupedia.net/emupedia-game-binding-of-isaac/" *Jugar*
  -UNO Online =🎮= "https://scuffeduno.online/" *Jugar*
  -Vimm's Lair [Roms][Emular] =🕹️= "https://vimm.net/vault"
  -WallpaperStore =⚙️= "https://angel06a.github.io/WallpaperStore/" *Utilizar*
  -WoWroMs [Roms][Emular] =🕹️= "https://wowroms.com/es/"
`,
  en: `
PC Games (emoji.windows)=🎮 (emoji.windows)=:
  -Alien Shooter "https://gogunlocked.com/alien-shooter-expansions-free-download/"
  -Alien Shooter 2: Reloaded "https://gogunlocked.com/alien-shooter-2-reloaded-free-download/"
  -Call of Duty Mobile PC [Chinese version] "https://codm.qq.com/main.shtml"
  -Call of Duty: Black Ops 1 "https://pivigames.blog/call-of-duty-black-ops-zombies-y-multiplayer-online/"
  -Call of Duty: Black Ops 2 "https://pivigames.blog/call-of-duty-black-ops-2-zombies-multiplayer-con-bots/"
  -Call of Duty: Modern Warfare 3 "https://pivigames.blog/call-of-duty-moder-warfare-3-con-multijugador-online/"
  -CB Servers Launcher [CoD Launcher] "https://docs.cbservers.xyz/launcher"
  -Clone Drone in the Danger Zone "https://www.mediafire.com/file/cs7iz3ckjpuoh6b/Clone_Drone_in_the_Danger_Zone.zip/file"
  -Cuphead "https://angel06a.github.io/angel06web/games/pc/cuphead/"
  -Downwell "https://elenemigos.com/app/downwell-descargar-gratis/21530"
  -Dragon Ball FighterZ "https://steamunlocked.org/dragon-ball-fighterz-free-download/"
  -Dragon Ball Sparking ZERO "https://pivigames.blog/dragon-ball-sparking-zero-oferta-25/"
  -Exiled Kingdoms "https://gogunlocked.com/exiled-kingdoms-free-download/"
  -Far Cry 3 "https://steamunlocked.org/far-cry-3-deluxe-edition-free-download/"
  -Flare "https://flarerpg.org/download/"
  -GTA III "https://www.blizzboygames.net/gta-iii-pc-full-espanol/"
  -GTA IV "https://pivigames.blog/grand-theft-auto-iv-episodes-from-liberty/"
  -GTA V "https://pivigames.blog/grand-theft-auto-v-premium-online-edition/"
  -GTA: San Andreas "https://www.blizzboygames.net/gta-san-andreas-pc-full-espanol/"
  -GTA: Vice City "https://www.blizzboygames.net/gta-vice-city-pc-full-espanol/"
  -Half-Life 1 Anthology "https://pivigames.blog/half-life-goty-edition/"
  -Halo Combat Evolved "https://steamunlocked.org/halo-combat-evolved-free-download/"
  -Injustice: Gods Among Us "https://steamunlocked.org/injustice-gods-among-us-ultimate-edition-free-download/"
  -Killer Instinct "https://pivigames.blog/killer-instinct/"
  -Left 4 Dead 2 "https://pivigames.blog/left-4-dead2-online-steam-ultima-version/"
  -Mario Kart 64 Port "https://github.com/sonicdcer/MarioKart64Recomp/releases" "https://vimm.net/vault/2649" *Download* *ROM*
  -Minecraft Bedrock "https://www.xbox.com/es-ES/games/store/minecraft-for-windows/9NBLGGH2JHXJ" "https://online-fix.me/games/sandbox/16708-minecraft-for-windows-po-seti.html" *Download* *OnlineFix*
  -Mortal Kombat Komplete Edition "https://steamunlocked.org/mortal-kombat-komplete-edition-free-download/"
  -Nidhogg 2 "https://steamunlocked.org/nidhogg-2-free-download/"
  -Nidhogg "https://steamunlocked.org/nidhogg-free-download/"
  -Naruto Shippuden: Ultimate Ninja STORM 3 "https://steamunlocked.org/naruto-shippuden-ultimate-ninja-storm-3-full-burst-hd-free-download/"
  -Pureya "https://steamunlocked.org/pureya-free-download/"
  -Quake III Arena "https://steamunlocked.org/quake-iii-arena-free-download/" "https://ioquake3.org/" *Base Game* *Ioquake3*
  -Rayman Legends "https://angel06a.github.io/angel06web/games/pc/rayman-legends/"
  -Serious Sam HD "https://steamunlocked.org/serious-sam-hd-the-second-encounter-free-download/"
  -Slayin DX "https://steamunlocked.org/slayin-dx-free-download/"
  -Slime Rancher "https://rentry.co/dzwd6zp4"
  -Sonic The Hedgehog 3D "https://rentry.co/m46az9tz"
  -Spore "https://steamunlocked.org/spore-collection-free-download/"
  -Street Fighter X Tekken "https://angel06a.github.io/angel06web/games/pc/SFTK/"
  -Super Mario 64 Port "https://sm64coopdx.com/" "https://vimm.net/vault/2764" *Download* *ROM*
  -Super Smash Flash 2 "https://www.supersmashflash.com/play/ssf2/downloads/"
  -The Legend of Zelda Port "https://www.shipofharkinian.com/" "https://vimm.net/vault/2637" *Download* *ROM*
  -Ultimate Marvel vs Capcom 3 "https://rentry.co/3b2zfkhf"
  -Undertale "https://pivigames.blog/undertale-en-espanol/"
PC Programs (emoji.windows)=⚙️ (emoji.windows)=:
  -Atlas OS [Optimizer] "https://github.com/Atlas-OS/Atlas"
  -Autoruns [Windows Registry] "https://www.google.com/url?q=https://download.sysinternals.com/files/Autoruns.zip&sa=D&source=docs&ust=1741690293775013&usg=AOvVaw3r6f1YvR1doRmskUjrBNyS"
  -BleachBit [Cleaning] "https://www.bleachbit.org/"
  -Bulk Crap Uninstaller [Cleaning] "https://www.bcuninstaller.com/"
  -CCleaner [Optimizer][Cleaning] "https://taiwebs.org/herramientas/ccleaner/"
  -CHDman [Compressor] "https://www.mediafire.com/file/gpehgmsgtnk3yz3/CHDman-0.276.zip/file"
  -CompactGUI [Optimizer][Compressor] "https://compactgui.org/"
  -DirectX Runtime [Installer] "https://www.techpowerup.com/download/directx-redistributable-runtime/"
  -DXVK [DirectX to Vulkan] "https://github.com/Digger1955/dxvk-gplall/releases" "https://github.com/doitsujin/dxvk/releases" *LowLatency* *Original*
  -Filmora [Video Editor] "https://taiwebs.org/programas/wondershare-filmora-portable/"
  -HidHide [Hide Controller] "https://github.com/nefarius/HidHide"
  -IdeapadToolkit [Lenovo Vantage Alternative] "https://github.com/reagcz/IdeapadToolkit" "https://www.mediafire.com/file/iehwb5o2yq2oenu/PowerBattery.dll/file" *Download* *Required File*
  -IObit Advanced SystemCare [Optimizer][Cleaning] "https://advanced-systemcare-ultimate.updatestar.com/es"
  -IObit Driver Booster [Drivers] "https://iobit-driver-booster-pro.updatestar.com/es"
  -IObit Unlocker [Unlock Files] "https://www.iobit.com/es/iobit-unlocker.php"
  -ITop Easy Desktop [Organize Folders] "https://itop-easy-desktop.updatestar.com/es"
  -LenovoController [Lenovo Vantage Alternative] "https://github.com/ViRb3/LenovoController"
  -Mirillis Action! [Screen Recorder] "https://descargaspcpro.net/mirillis-action-programa-para-grabar-la-pantalla-y-videojuegos-de-tu-pc/"
  -MPO-GPU-FIX [Optimizer] "https://github.com/RedDot-3ND7355/MPO-GPU-FIX"
  -O&O ShutUp10++ [Disable Services] "https://www.oo-software.com/es/shutup10"
  -OptimizerDuck [Optimizer] "https://optimizerduck.vercel.app/"
  -Photopea Offline [Image Editor][By Angel06] "https://www.mediafire.com/file/mi1kpb5oyvaint8/Photopea_Offline.zip/file"
  -Process Lasso [Optimizer] "https://descargaspcpro.net/bitsum-process-lasso-pro-herramienta-de-optimizacion-y-automatizacion-de-la-cpu-en-tiempo-real/"
  -qBittorrent "https://www.qbittorrent.org/"
  -Quick CPU [Optimizer] "https://coderbag.com/product/quickcpu"
  -Ratiborus KMS Tools [Activator] "https://descargaspcpro.net/ratiborus-kms-tools-coleccion-de-activadores-para-todos-los-windows-y-office/"
  -RetroBat [Frontend][Emulate] =🕹️= "https://www.retrobat.org/descargar/"
  -TeraBox [Cloud Storage] "https://www.terabox.com/"
  -UniGetUI [Updater] "https://devolutions.net/unigetui/"
  -Upscayl [Image Upscaler] "https://upscayl.org/download"
  -VigemBus [Controller Driver] "https://vigembusdriver.com/download/"
  -Visual C++ Runtime [Installer] "https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/"
  -WinRAR [Compress] "https://winrar.es/descargas" "https://www.mediafire.com/file/fpjwybjxfk5emug/rarreg.key/file" *Download* *Crack*
  -Wintoys [Optimizer][Cleaning] "https://apps.microsoft.com/detail/9p8ltpgcbzxd?hl=es-ES&gl=ES"
  -X360CE [Controller Emulation] =🎮= "https://www.x360ce.com/"
  -XOutput [Controller Emulation] =🎮= "https://xoutput.org/"
Android Games (emoji.android)=🎮 (emoji.android)=:
  -Alien Shooter "https://www.mediafire.com/file/qtxntb41f2tfaib/Alien_Shooter_1.2.5.apk/file"
  -Call of Duty: Black Ops Zombies "https://www.mediafire.com/file/a9cb3i70ft7ms7n/COD_BOZ_1.0.11.zip/file"
  -Crash Bandicoot: On the Run [Offline] "https://agmod.org/crash-bandicoot-on-the-run-full-offline-apk-obb/"
  -Cuphead "https://apkvision.org/games/action/cuphead-100069/"
  -Dead Effect 2 "https://agmod.org/dead-effect-2/"
  -Dead Space "https://agmod.org/dead-space/"
  -Downwell "https://www.mediafire.com/file/kgf4ethmk88byy3/Downwell_1.1.1.apk/file"
  -Dragon Ball Tap Battle "https://www.mediafire.com/file/sga4y11ur7s44b3/Dragon_Ball_Tap_Battle_1.4.apk/file"
  -Exiled Kingdoms "https://apkvision.org/games/role-playing/exiled-kingdoms-rpg-10725/"
  -Fast Food Rampage "https://www.mediafire.com/file/g2f8trc7ezkqrmy/Fast_Food_Rampage_1.0.8.apk/file"
  -GTA III "https://apkvision.org/games/action/grand-theft-auto-3-apk-3166/"
  -GTA: Chinatown Wars "https://apkvision.org/games/action/gta-chinatown-wars-8293/"
  -GTA: Liberty City Stories "https://apkvision.org/games/action/gta-liberty-city-stories-8337/"
  -GTA: San Andreas "https://apkvision.org/games/action/grand-theft-auto-san-andreas-apk-106-2824/"
  -GTA: Vice City "https://apkvision.org/games/action/grand-theft-auto-vice-city-apk-2820/"
  -Lego DC Mighty Micros "https://www.mediafire.com/file/1i6ga7bi2qo1voh/LEGO_DC_Mighty_Micros_1.7.1418.apk/file"
  -Minecraft Bedrock "https://mcpelife.com/download/"
  -NARUTO: Ultimate Ninja STORM "https://apkvision.org/games/action/naruto-ultimate-ninja-storm-124113/"
  -Paladog "https://www.mediafire.com/file/1xbi8es1hh3sscx/Paladog_2.2.0.apk/file"
  -Pureya "https://www.mediafire.com/file/6n6i3m4cso48zfd/Pureya_1.0.15.apk/file"
  -Run & Gun: Banditos "https://www.mediafire.com/file/cu23w1yl9t4qp64/Run_%2526_Gun_BANDITOS_1.3.2.apk/file"
  -Slayin "https://www.mediafire.com/file/aya455c8ig96hjw/Slayin_2.0.13.apk/file"
  -Slime Rancher "https://apkvision.org/games/action/slime-rancher-106836/"
  -Street Fighter IV CE "https://apkvision.org/games/action/street-fighter-iv-ce-netflix-128855/"
  -Super Mario 64 Port "https://github.com/ManIsCat2/sm64coopdx/releases" "https://vimm.net/vault/2764" *Download* *ROM*
  -The Legend of Zelda Port "https://github.com/linkzenic/Shipwright-Android/releases" "https://vimm.net/vault/2637" *Download* *ROM*
  -Zombie Avengers Dreamsky Stickman War "https://www.mediafire.com/file/7qmtqoinva2itn4/Zombie_Avengers_Dreamsky_Stickman_War_2.0.3.apk/file"
Android Programs (emoji.android)=⚙️ (emoji.android)=:
  -ARMSX2 [Emulate PS2] =🕹️= "https://play.google.com/store/apps/details?id=come.nanodata.armsx2"
  -Azahar [Emulate 3DS] =🕹️= "https://play.google.com/store/apps/details?id=io.github.lime3ds.android"
  -CapCut Pro [Video Editor] "https://www.mediafire.com/file/wvhjm75wj4cqdoc/CapCut+Pro+v13.9.0_(AndroidApkData.net).apk/file"
  -Daijishō [Frontend][Emulate] =🕹️= "https://play.google.com/store/apps/details?id=com.magneticchen.daijishou"
  -Filmora [Video Editor] "https://apkpure.com/es/filmora-movie-video-editor/com.wondershare.filmorago"
  -Gestor de archivos + "https://apkretro.com/file-manager-premium-apk-download/"
  -LibreTorrent "https://f-droid.org/es/packages/org.proninyaroslav.libretorrent/"
  -Linkboy [Emulate GBA & GBC] =🕹️= "https://play.google.com/store/apps/details?id=com.pixelrespawn.linkboy"
  -LuckyPatcher "https://www.mediafire.com/file/rej7uf1t7w48x0u/luckypatcher.apk/file"
  -M64Plus FZ Pro [Emulate N64] =🕹️= "https://apkretro.com/m64plus-fz-pro-emulator-apk-full-android/"
  -MAME4droid Current [Emulate ARCADE] =🕹️= "https://github.com/seleuco/MAME4droid-Current/releases"
  -NES.Emu [Emulate NES] =🕹️= "https://apkretro.com/nes-emu-apk-download/"
  -Pizza Boy GBA Pro [Emulate GBA] =🕹️= "https://apkretro.com/pizza-boy-gba-pro-apk-download/"
  -PPSSPP Gold [Emulate PSP] =🕹️= "https://apkretro.com/ppsspp-gold-apk-download/"
  -RAR [Premium Unlocked] "https://apkretro.com/rar-premium-apk-download/"
  -ReVanced Manager Plus "https://vanced.to/revanced-manager"
  -Super File "https://liteapks.com/super-file.html"
  -VPN Super Unlimited Proxy [Premium Unlocked] "https://liteapks.com/vpn-super-unlimited-proxy.html"
Websites (emoji.web)=(emoji.web)=:
  -Bios [ROMs][Emulate] =🕹️= "https://github.com/Angel06a/Bios-RetroBat"
  -BT4 HD [DBZ BT4 Texture Pack][By Angel06] =⚙️= "https://angel06a.github.io/BT4-HD/"
  -BuscaMinas [By Angel06] =🎮= "https://angel06a.github.io/angel06web/hub/minesweeper/" *Play*
  -DaedalOS [Desktop] =⚙️= "https://dustinbrett.com/" *Use*
  -Flappy Bird =🎮= "https://emupedia.net/emupedia-game-flappy-bird/" *Play*
  -Friday Night Funkin =🎮= "https://ninja-muffin24.itch.io/funkin" *Play*
  -GamesGX [PS2 ROMs][Emulate] =🕹️= "https://www.gamesgx.net/"
  -Icon Converter =⚙️= "https://redketchup.io/icon-converter" *Use*
  -Jetpack Joyride =🎮= "https://emupedia.net/emupedia-game-jetpack-joyride/" *Play*
  -MarkEditor [By Angel06] =⚙️= "https://angel06a.github.io/angel06web/hub/markeditor/" *Use*
  -NoPayStation [PS3 ROMs][Emulate] =🕹️= "https://nopaystation.com/browse"
  -OpenLara [Tomb Raider] =🎮= "https://emupedia.net/emupedia-game-tomb-raider/" *Play*
  -Photopea [Image Editor] =⚙️= "https://www.photopea.com/" *Use*
  -Puter [Desktop] =⚙️= "https://puter.com/"
  -RetroGames [Emulate] =🕹️= "https://www.retrogames.onl/" *Play*
  -ROMSFUN [ROMs][Emulate] =🕹️= "https://romsfun.com/"
  -Slash FRVR [Fruit Ninja] =🎮= "https://slash.frvr.com/es/" *Play*
  -Subway Surfers =🎮= "https://g2.igroutka.ru/games/164/ZXLa594fek6p7nVR/10/subway_surfers_classic/" *Play*
  -Super Mario 64 Port =🎮= "https://notan127.github.io/SM64-PC-Port-WebGL/" *Play*
  -Temple Run 2 =🎮= "https://emupedia.net/emupedia-game-temple-run2/" *Play*
  -TempMail =⚙️= "https://temp-mail.org/es/" *Use*
  -The Binding of Isaac =🎮= "https://emupedia.net/emupedia-game-binding-of-isaac/" *Play*
  -UNO Online =🎮= "https://scuffeduno.online/" *Play*
  -Vimm's Lair [ROMs][Emulate] =🕹️= "https://vimm.net/vault"
  -WallpaperStore =⚙️= "https://angel06a.github.io/WallpaperStore/" *Use*
  -WoWroMs [ROMs][Emulate] =🕹️= "https://wowroms.com/es/"
`
};
